### ISSUE TITLE
Can't install SynEdit

### ISSUE THREAD

**Issue by VadimBorzov** [TurboPack-Tokyo/SynEdit#4]
Hello.
Can't understand what I'm doing wrong.
Delphi 10.2 Version 25.0.29039.2004 

Open project SynEditDD.dproj (32863bytes 9-dec-2017)
Right click "Install"
[dcc32 Fatal Error] SynEditDD.dpk(35): E2202 Required package 'designide' not found

Of course, designide.dcp exists in ...\lib\win32\release directory
And this path is in Delphi's LIB path

Ok. Let's copy designide.dcp to SynEditDD.dproj directory
After this I have another error

[dcc32 Fatal Error] SynHighlighterManager.pas(92): E2213 Bad packaged unit format: designide.dcp.DesignIntf - Expected version: 32.0, Windows Unicode(x64) Found version: 32.0, Windows Unicode(x86)

So, it seems, that installation try to find 64bit designide.dcp, which of course doesn't exist.

Trying to google the problem, have found this
http://docwiki.embarcadero.com/Libraries/Berlin/en/DesignIntf

Have added this option to the package project but result is the same :(

Any ideas?
Thanks in advance

Vadim

**Comment by pyscripter** [comment]
Have you installed the runtime package SynEditD first?

**Comment by VadimBorzov** [comment]
Yes I  tried open SynEditDR.dpoj and compile it.
But without success

[dcc32 Error] SynEditDR.dpk(40): E2200 Package 'SynEditDR' already contains unit 'SynTextDrawer'
[dcc32 Error] SynEditDR.dpk(41): E2200 Package 'SynEditDR' already contains unit 'SynAutoCorrect'
[dcc32 Error] SynEditDR.dpk(42): E2200 Package 'SynEditDR' already contains unit 'SynAutoCorrectEditor'
[dcc32 Error] SynEditDR.dpk(43): E2200 Package 'SynEditDR' already contains unit 'SynCompletionProposal'
[dcc32 Error] SynEditDR.dpk(44): E2200 Package 'SynEditDR' already contains unit 'SynDBEdit'
[dcc32 Error] SynEditDR.dpk(45): E2200 Package 'SynEditDR' already contains unit 'SynEdit'
....
[dcc32 Error] SynEditDR.dpk(140): E2200 Package 'SynEditDR' already contains unit 'SynHighlighterJSON'
[dcc32 Fatal Error] SynEditDR.dpk(141): E2226 Compilation terminated; too many errors

PS Read.me said nothing about need to compile run-time package. I have decided it will be done automatically when install design-time package

**Comment by pyscripter** [comment]
Strange works here fine.
In Delphi you always need to install runtime packages (if they exist) before installing design-time packages.

You may try to remove from installed packages all Synedit packages, delete compiled packages, redownload, source code for packages to make sure they are correct (Delphi has a habbit of modifying them) and try again.

**Comment by VadimBorzov** [comment]
I have done the followings:

- delete files SynEdit* from DCP and BPL output dirs
  ...\dcp\win64\synEditDR.a
  ...\dcp\win64\synEditDR.bpi
  ...\dcp\win64\synEditDR.dcp
  ...\bpl\win64\synEditDR250.bpl

- in "Component\Install Packages..." I can't find anything concerning SynEdit

- unzip again synEdit-master.zip

- close and open Delphi IDE

- open project SynEditDR.proj

- Compile

- Process begins, but ends with error

Compiling SynEditDR.dproj (Release, Win32)
brcc32 command line for "SynEditDR.vrc"
  c:\program files (x86)\embarcadero\studio\19.0\bin\cgrc.exe -c65001 "SynEditDR.vrc" -foSynEditDR.res 
dcc64 command line for "SynEditDR.dpk"
  c:\program files (x86)\embarcadero\studio\19.0\bin\dcc64.exe -$J+ -$D0 -$L- -$Y- --no-config -M -Q -Z -TX.bpl 
  -AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;
  DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DRELEASE -I"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\HP\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\Components\EhLib\Lib\Win64\Release" -LEC:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64 
  -LNC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64 -NU.\Win64\Release -NSData.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Vcl;Vcl.Imaging;
  Vcl.Touch;Vcl.Samples;Vcl.Shell;System;Xml;Data;Datasnap;Web;Soap;Winapi;System.Win;Bde; -O"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win64\release";C:\Users\HP\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\19.0\include";"C:\Program Files (x86)\Embarcadero\Studio\19.0\Components\EhLib\Lib\Win64\Release" -R"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win64\release";C:\Users\HP\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\19.0\include";"C:\Program Files (x86)\Embarcadero\Studio\19.0\Components\EhLib\Lib\Win64\Release" -U"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win64\release";C:\Users\HP\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\19.0\include";"C:\Program Files (x86)\Embarcadero\Studio\19.0\Components\EhLib\Lib\Win64\Release" -K00400000 
  --description:"TurboPack SynEdit Delphi runtime package" -JL -NBC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64 
  -NH..\..\source\hpp\Win64\Release -NOC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64   SynEditDR.dpk   
Can't load package SynEditDR250.bpl. Can't find the specified file
[Fatal Error] Can't load package SynEditDR250.bpl. Can't find the specified file

- But nevertheless 4 files were created (only in win64 dir)
  ...\dcp\win64\synEditDR.a	//what's this ?
  ...\dcp\win64\synEditDR.bpi
  ...\dcp\win64\synEditDR.dcp
  ...\bpl\win64\synEditDR250.bpl


I have another installed package. It works without problems and its files are located in \dcp\* \bpl\* \dcp\win64\* bpl\win64\*.


PS. May be another Delphi version (2010) and old SynEdit inside it can cause problems ?

**Comment by pyscripter** [comment]
\bpl\win64\synEditDR250.bpl  ??

To install packages in the IDE you only need to compile and install packages for 32-bit platform.  The IDE is 32 bit.

**Comment by VadimBorzov** [comment]
You told that firstly I have to compile runtime package.
This is exactly what I described above.
First step - runtime package SynEditDR.dproj. Nothing else.
Open project SynEditDR.dproj and choose "Compile"  in pop-up menu. 
That's all.
And got error... :(

**Comment by pyscripter** [comment]
You are compiling for 64 bits.  You need to compile for 32 bits.

**Comment by VadimBorzov** [comment]
After opening the project platform is 32bit by default. I did not change it.
Now I have deleted node Win64 from project at all. But result is the same

Compiling SynEditDR.dproj (Release, Win32)
brcc32 command line for "SynEditDR.vrc"
  c:\program files (x86)\embarcadero\studio\19.0\bin\cgrc.exe -c65001 "SynEditDR.vrc" -foSynEditDR.res 
dcc64 command line for "SynEditDR.dpk"
  c:\program files (x86)\embarcadero\studio\19.0\bin\dcc64.exe -$J+ -$D0 -$L- -$Y- --no-config -M -Q -Z -TX.bpl 
  -AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;
  DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DRELEASE -I"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\HP\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\Components\EhLib\Lib\Win64\Release" -LEC:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64 
  -LNC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64 -NU.\Win64\Release -NSData.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Vcl;Vcl.Imaging;
  Vcl.Touch;Vcl.Samples;Vcl.Shell;System;Xml;Data;Datasnap;Web;Soap;Winapi;System.Win;Bde; -O"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win64\release";C:\Users\HP\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\19.0\include";"C:\Program Files (x86)\Embarcadero\Studio\19.0\Components\EhLib\Lib\Win64\Release" -R"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win64\release";C:\Users\HP\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\19.0\include";"C:\Program Files (x86)\Embarcadero\Studio\19.0\Components\EhLib\Lib\Win64\Release" -U"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win64\release";C:\Users\HP\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\19.0\include";"C:\Program Files (x86)\Embarcadero\Studio\19.0\Components\EhLib\Lib\Win64\Release" -K00400000 
  --description:"TurboPack SynEdit Delphi runtime package" -JL -NBC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64 
  -NH..\..\source\hpp\Win64\Release -NOC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64   SynEditDR.dpk   
Can't load package SynEditDR250.bpl. Can't find the specified file

It seems that something wrong in my Computer or Delphi installation/settings.

**Comment by VadimBorzov** [comment]
Wow! I did it.
Who can think that the problem was in windows enviroment variable PLATFORM=Win64
Now I have remebered that initially it was PLATFORM=HPD (HP computer with preinstall winwows)
Later I renamed into PLATFORM=Win64. Dont't know why I did it.

And now in Delphi IDE Tools\Options I create override Platform with empty value and voila...

Pyscripter, thanks for your help.

Vadim
